version: '2'
services:
      
  CTFPoller:
    image: sporky/ctfmonitor:poller
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: service=static
      
  CTFStatus:
    image: sporky/ctfmonitor:status
    stdin_open: true
    tty: true
    ports:
    - 5678:5000/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: service=static
      
  CTFReporter:
    image: sporky/ctfmonitor:reporter
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: service=static
      
  CTFBlinker:
    image: bepsoccer/blue-team-status
    stdin_open: true
    tty: true
    ports:
    - 8443:8443/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: service=config