version: '2'
catalog:
  name: CTFMonitor
  version: 0.8.0
  description: |
    Stack of containers to poll, report and score the defense activities of this fine CTF
services:
  AMPQ:
    retain_ip: true
    scale: 1
    start_on_create: true
  CTFPoller:
    scale: 1
    start_on_create: true
  CTFStatus:
    scale: 1
    start_on_create: true
  CTFReporter:
    scale: 1
    start_on_create: true
