  CTFamqp:
    image: rabbitmq:3.6-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: ctfadmin
      RABBITMQ_DEFAULT_PASS: adminctf
    stdin_open: true
    tty: true
    ports:
    - 5672:5672/tcp
    - 15672:15672/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: service=static
