version: '2'
catalog:
  name: ctfconfigs
  version: 1.0-rancher2
  description: |
    Central configs
  maintainer: Brent Imhoff <bimhoff@planetspork.com>
services:
  consul2:
    scale: 1
    start_on_create: true
  consul3:
    scale: 1
    start_on_create: true
  consul1:
    scale: 1
    start_on_create: true
