version: '2'
services:

  ctfmysql:
    image: mysql/mysql-server:5.7
    hostname: rtbmysql
    environment:
      MYSQL_ROOT_PASSWORD: ctfadminverylongpassword
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: rootthebox
    stdin_open: true
    tty: true
    ports:
    - 6603:3306/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: service=board
      
  ctfscore:
    image: sporky/scoreboard
    hostname: ctfscore
    environment:
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ctfmysql
      MYSQL_PORT: ${MYSQL_PORT}
      CTF_ADMIN: ${CTF_ADMIN}
      CTF_PASSWD: ${CTF_PASSWD}
    stdin_open: true
    tty: true
    ports:
    - 80:8888/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: service=board
      io.rancher.sidekicks: ctfmysql,ctfmemcache
    command:
      - /RootTheBox/setup/container_setup.sh
    depends_on:
      - ctfmysql
      
  ctfmemcache:
    image: memcached
    stdin_open: true
    tty: true
    ports:
    - 11011:11011/tcp
    labels:
      io.rancher.container.pull_image: always
      
  ctfbuild:
    image: sporky/ctfbuild
    hostname: ctfbuild
    environment:
      MYSQL_PASS: ${MYSQL_PASS}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_HOST: ctfmysql
      MYSQL_PORT: ${MYSQL_PORT}
      CTF_ADMIN: ${CTF_ADMIN}
      CTF_PASSWD: ${CTF_PASSWD}
    stdin_open: true
    tty: true
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: service=board
      io.rancher.container.start_once: 'true'
      io.rancher.container.requested_ip: 10.42.1.1
      