version: '2'
services:
  ctfmysql:
    image: mysql/mysql-server
    hostname: rtbmysql
    environment:
      MYSQL_ROOT_PASSWORD: ctfadminverylongpassword
      MYSQL_USER: ctfadmin
      MYSQL_PASSWORD: ctfadminverylongpassword
      MYSQL_DATABASE: rootthebox
    stdin_open: true
    tty: true
    ports:
    - 6603:3306/tcp
    labels:
      io.rancher.container.pull_image: always
  CTFScore:
    image: sporky/scoreboard
    hostname: ctfscore
    stdin_open: true
    tty: true
    ports:
    - 80:8888/tcp
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label: service=board
      io.rancher.sidekicks: ctfmysql,ctfmemcache
    command:
      - /PrivRootTheBox/setup/container_setup.sh
  ctfmemcache:
    image: memcached
    stdin_open: true
    tty: true
    ports:
    - 11011:11011/tcp
    labels:
      io.rancher.container.pull_image: always
  CTFBuild:
    image: sporky/ctfbuild
    stdin_open: true
    tty: true
    labels:
      io.rancher.scheduler.affinity:host_label: service=board
      io.rancher.container.start_once: 'true'
      io.rancher.container.requested_ip: 10.42.1.1
      