version: '2'
services:
  team1:
    image: shane-ctf:1.4
    stdin_open: true
    tty: true
    ports:
    - 8000:8000/tcp
    command:
    - node
    - ctf-app.js
    - "1"
    labels:
      io.rancher.scheduler.affinity:host_label: role=protected
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: team=1
  team2:
    image: shane-ctf:1.4
    stdin_open: true
    tty: true
    ports:
    - 8000:8000/tcp
    command:
    - node
    - ctf-app.js
    - "2"
    labels:
      io.rancher.scheduler.affinity:host_label: role=protected
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: team=2
  team3:
    image: shane-ctf:1.4
    stdin_open: true
    tty: true
    ports:
    - 8000:8000/tcp
    command:
    - node
    - ctf-app.js
    - "3"
    labels:
      io.rancher.scheduler.affinity:host_label: role=protected
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: team=3
  team4:
    image: shane-ctf:1.4
    stdin_open: true
    tty: true
    ports:
    - 8000:8000/tcp
    command:
    - node
    - ctf-app.js
    - "4"
    labels:
      io.rancher.scheduler.affinity:host_label: role=protected
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: team=4
  team5:
    image: shane-ctf:1.4
    stdin_open: true
    tty: true
    ports:
    - 8000:8000/tcp
    command:
    - node
    - ctf-app.js
    - "5"
    labels:
      io.rancher.scheduler.affinity:host_label: role=protected
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: team=5
  team6:
    image: shane-ctf:1.4
    stdin_open: true
    tty: true
    ports:
    - 8000:8000/tcp
    command:
    - node
    - ctf-app.js
    - "6"
    labels:
      io.rancher.scheduler.affinity:host_label: role=protected
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: team=6
  team7:
    image: shane-ctf:1.4
    stdin_open: true
    tty: true
    ports:
    - 8000:8000/tcp
    command:
    - node
    - ctf-app.js
    - "7"
    labels:
      io.rancher.scheduler.affinity:host_label: role=protected
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: team=7
  team8:
    image: shane-ctf:1.4
    stdin_open: true
    tty: true
    ports:
    - 8000:8000/tcp
    command:
    - node
    - ctf-app.js
    - "8"
    labels:
      io.rancher.scheduler.affinity:host_label: role=protected
      io.rancher.scheduler.global: 'true'
      io.rancher.scheduler.affinity:host_label: team=8
  sshreporter:
    image: sporky/sshd
    stdin_open: true
    tty: true
    ports:
    - 2222:22/tcp
    labels:
      io.rancher.scheduler.affinity:host_label: role=protected
      io.rancher.container.pull_image: always
      io.rancher.scheduler.global: 'true'
